package com.bandit1250.fuelmonitor;

import java.io.*;
import java.util.*;

/**
 * Retained development-only Suzuki/Denso read-test helpers.
 *
 * This class now contains only the protocol experiments still exposed from
 * DEV / EXPERIMENTAL:
 * - ELM transmit/message-length testing
 * - conservative Denso/K-line read-only compatibility tests
 *
 * Legacy dead ends have been removed:
 * - automatic ECU discovery / RequestUpload probing
 * - KWP 0x30 service/local-ID probing
 * - generic 0x23 memory dump/read path
 *
 * No erase, flash-write, actuator-control or guessed security-key operations
 * are performed by the retained tests.
 */
public final class EcuMemoryReader {
    private EcuMemoryReader() {}

    private static String safeRequest(
            SuzukiSds sds,
            String request,
            long timeoutMs
    ) {
        try {
            return sds.requestRaw(request + " 1", timeoutMs);
        } catch (IOException e) {
            return "I/O ERROR: " + e.getMessage();
        }
    }

    private static boolean isPositiveService(String response, int service) {
        if (response == null) return false;

        String upper = response.toUpperCase(Locale.US);
        if (upper.contains("NO DATA") ||
                upper.contains("ERROR") ||
                upper.contains("UNABLE") ||
                upper.contains("STOPPED")) {
            return false;
        }

        String hex = upper.replaceAll("[^0-9A-F]", "");
        String marker = String.format(Locale.US, "%02X", service);

        return hex.startsWith(marker) || hex.contains(marker);
    }

    public static final class ElmLengthTestResult {
        public final int largestEcuSeenBytes;
        public final int firstQuestionMarkBytes;
        public final boolean questionMarkAlsoWithoutResponseCount;
        public final String report;

        ElmLengthTestResult(
                int largestEcuSeenBytes,
                int firstQuestionMarkBytes,
                boolean questionMarkAlsoWithoutResponseCount,
                String report
        ) {
            this.largestEcuSeenBytes = largestEcuSeenBytes;
            this.firstQuestionMarkBytes = firstQuestionMarkBytes;
            this.questionMarkAlsoWithoutResponseCount =
                    questionMarkAlsoWithoutResponseCount;
            this.report = report;
        }
    }

    /**
     * Diagnose whether long-request "?" replies are generated by the ELM/V-LINK
     * rather than the Suzuki ECU.
     *
     * Safety: the test uses only Suzuki local-identifier read service 0x1A,
     * identifier 0x91, which is already known to return the ECU family ID.
     * Extra zero bytes deliberately make the request malformed but do not turn
     * it into a write, routine, actuator, reset or programming operation.
     */
    public static ElmLengthTestResult testElmMessageLength(SuzukiSds sds)
            throws IOException {
        StringBuilder report = new StringBuilder();

        report.append("ELM / K-LINE MESSAGE LENGTH TEST\n");
        report.append("Uses read-only ECU ID request 1A91 with zero padding.\n\n");

        // Record adapter identity/protocol and explicitly re-assert Allow Long.
        String ati = sds.requestRaw("ATI", 2500);
        report.append("ATI -> ").append(oneLine(ati)).append("\n");

        String atdpn = sds.requestRaw("ATDPN", 2500);
        report.append("ATDPN -> ").append(oneLine(atdpn)).append("\n");

        String atal = sds.requestRaw("ATAL", 2500);
        report.append("ATAL -> ").append(oneLine(atal)).append("\n\n");

        // Prove the known-good ECU ID read before doing any padding.
        String baseline = timedRequestReport(
                report,
                sds,
                "1A91",
                true
        );

        if (!containsPositiveLocalIdentifier(baseline, 0x91)) {
            report.append("\nBaseline 1A91 did not return the expected 5A91. ");
            report.append("Length test aborted so an unrelated link fault is not ");
            report.append("mistaken for an adapter limit.");

            return new ElmLengthTestResult(
                    0,
                    0,
                    false,
                    report.toString().trim()
            );
        }

        int largestEcuSeen = 2;
        int firstQuestion = 0;
        boolean questionWithoutCount = false;

        report.append("\nPadded request sweep\n");
        report.append("bytes  request/result\n");

        // 2 bytes = normal 1A 91. Sweep beyond the region where the previous
        // 0x35 discovery first produced '?'.
        for (int totalBytes = 2; totalBytes <= 16; totalBytes++) {
            String request = padded1A91(totalBytes);

            long t0 = System.nanoTime();
            String response;

            try {
                response = sds.requestRaw(request + " 1", 4500);
            } catch (IOException e) {
                response = "I/O ERROR: " + e.getMessage();
            }

            long elapsedMs = Math.max(
                    0L,
                    (System.nanoTime() - t0) / 1_000_000L
            );

            report.append(String.format(
                    Locale.US,
                    "%2d B  %s  -> %s  (%d ms)\n",
                    totalBytes,
                    request,
                    oneLine(response),
                    elapsedMs
            ));

            boolean ecuSeen =
                    containsPositiveLocalIdentifier(response, 0x91) ||
                    containsNegativeForService(response, 0x1A);

            if (ecuSeen) {
                largestEcuSeen = totalBytes;
            }

            if (isQuestionMark(response)) {
                if (firstQuestion == 0) {
                    firstQuestion = totalBytes;
                }

                // Critical cross-check: retry the exact same raw data without
                // ELM's trailing "expect one response" count. If '?' remains,
                // the evidence for a local adapter/parser limit is much stronger.
                long t1 = System.nanoTime();
                String retry;

                try {
                    retry = sds.requestRaw(request, 4500);
                } catch (IOException e) {
                    retry = "I/O ERROR: " + e.getMessage();
                }

                long retryMs = Math.max(
                        0L,
                        (System.nanoTime() - t1) / 1_000_000L
                );

                report.append(String.format(
                        Locale.US,
                        "      same data WITHOUT trailing response-count -> %s  (%d ms)\n",
                        oneLine(retry),
                        retryMs
                ));

                if (isQuestionMark(retry)) {
                    questionWithoutCount = true;
                }
            }
        }

        // Finish with another known-good request. This proves the ECU/K-Line
        // connection still functions after the long-message tests.
        report.append("\nPost-test link check\n");
        String finalBaseline = timedRequestReport(
                report,
                sds,
                "1A91",
                true
        );

        report.append("\nINTERPRETATION\n");

        if (firstQuestion > 0 &&
                largestEcuSeen > 0 &&
                firstQuestion == largestEcuSeen + 1 &&
                questionWithoutCount &&
                containsPositiveLocalIdentifier(finalBaseline, 0x91)) {
            report.append(
                    "Strong evidence that '?' is generated locally by the " +
                    "ELM/V-LINK at the request-length boundary, not by the ECU.\n"
            );
            report.append("Largest padded request seen answering from ECU: ")
                    .append(largestEcuSeen)
                    .append(" bytes.\n");
            report.append("First local '?' request length: ")
                    .append(firstQuestion)
                    .append(" bytes.\n");
        } else if (firstQuestion > 0) {
            report.append(
                    "A '?' boundary was observed, but the pattern is not clean " +
                    "enough to call it conclusively local. Review the timings and " +
                    "with/without-response-count retries above.\n"
            );
        } else {
            report.append(
                    "No '?' boundary was found up to 16 request bytes. The earlier " +
                    "question marks were therefore not reproduced by this read-only test.\n"
            );
        }

        return new ElmLengthTestResult(
                largestEcuSeen,
                firstQuestion,
                questionWithoutCount,
                report.toString().trim()
        );
    }

    private static String timedRequestReport(
            StringBuilder report,
            SuzukiSds sds,
            String request,
            boolean addResponseCount
    ) {
        long t0 = System.nanoTime();
        String response;

        try {
            response = sds.requestRaw(
                    addResponseCount ? request + " 1" : request,
                    4500
            );
        } catch (IOException e) {
            response = "I/O ERROR: " + e.getMessage();
        }

        long elapsedMs = Math.max(
                0L,
                (System.nanoTime() - t0) / 1_000_000L
        );

        report.append(request)
                .append(addResponseCount ? " 1" : "")
                .append(" -> ")
                .append(oneLine(response))
                .append(" (")
                .append(elapsedMs)
                .append(" ms)\n");

        return response;
    }

    private static String padded1A91(int totalBytes) {
        if (totalBytes < 2) {
            throw new IllegalArgumentException("1A91 needs at least 2 bytes");
        }

        StringBuilder s = new StringBuilder(totalBytes * 2);
        s.append("1A91");

        for (int i = 2; i < totalBytes; i++) {
            s.append("00");
        }

        return s.toString();
    }

    private static boolean containsPositiveLocalIdentifier(
            String response,
            int identifier
    ) {
        if (response == null) return false;

        String hex = response.toUpperCase(Locale.US)
                .replaceAll("[^0-9A-F]", "");

        return hex.contains(
                String.format(Locale.US, "5A%02X", identifier & 0xFF)
        );
    }

    private static boolean containsNegativeForService(
            String response,
            int service
    ) {
        if (response == null) return false;

        String hex = response.toUpperCase(Locale.US)
                .replaceAll("[^0-9A-F]", "");

        return hex.contains(
                String.format(Locale.US, "7F%02X", service & 0xFF)
        );
    }

    private static boolean isQuestionMark(String response) {
        if (response == null) return false;

        return response.trim().equals("?") ||
                response.trim().endsWith("?");
    }

    public static final class DensoReadOnlyTestResult {
        public final String report;
        public final String supported1A;
        public final String supported21;
        public final boolean normalSdsRestored;

        DensoReadOnlyTestResult(
                String report,
                String supported1A,
                String supported21,
                boolean normalSdsRestored
        ) {
            this.report = report;
            this.supported1A = supported1A;
            this.supported21 = supported21;
            this.normalSdsRestored = normalSdsRestored;
        }
    }

    /**
     * Additional conservative Denso/Suzuki discovery.
     *
     * The diagnostic requests are all read-only (0x1A, 0x21 and 0x22).
     * The transport tests temporarily change only ELM/K-Line communication
     * parameters, then restore the normal Suzuki SDS fast-init session.
     *
     * No ECU reset, security key, programming-session selection, write,
     * erase, routine, actuator, download or flash command is sent.
     */
    public static DensoReadOnlyTestResult testDensoReadOnlyPaths(
            SuzukiSds sds
    ) throws IOException {
        StringBuilder report = new StringBuilder();

        report.append("DENSO / SUZUKI READ-ONLY COMPATIBILITY TEST\n");
        report.append("ECU: known family ID 32920-18H0* via 1A91\n");
        report.append("No write/erase/reset/routine/actuator/security-key commands used.\n\n");

        report.append("[1] Baseline SDS identity\n");
        String baseline = safeRequest(sds, "1A91", 4000);
        report.append("1A91 -> ").append(oneLine(baseline)).append("\n");

        report.append("\n[2] Suzuki/Denso ECU-identification local IDs 0x80..0x9F\n");
        int idHits = 0;
        ArrayList<String> supported1A = new ArrayList<>();

        for (int id = 0x80; id <= 0x9F; id++) {
            String request = String.format(Locale.US, "1A%02X", id);
            String response = safeRequest(sds, request, 1800);

            if (isPositiveService(response, 0x5A)) {
                idHits++;
                supported1A.add(request);
                report.append(request)
                        .append(" -> ")
                        .append(oneLine(response));

                String ascii = printablePayloadAfter(response, 0x5A, id);
                if (!ascii.isEmpty()) {
                    report.append("   ASCII: ").append(ascii);
                }
                report.append("\n");
            }
        }

        report.append("Positive 0x1A identifiers: ")
                .append(idHits)
                .append(" / 32\n");

        report.append("\n[3] ReadDataByLocalIdentifier 0x21, IDs 00..1F\n");
        int localHits = 0;
        ArrayList<String> supported21 = new ArrayList<>();

        for (int id = 0x00; id <= 0x1F; id++) {
            String request = String.format(Locale.US, "21%02X", id);
            String response = safeRequest(sds, request, 1800);
            String hex = compactHex(response);
            String positive = String.format(Locale.US, "61%02X", id);

            if (hex.contains(positive)) {
                localHits++;
                supported21.add(request);
                report.append(request)
                        .append(" -> ")
                        .append(oneLine(response))
                        .append("\n");
            }
        }

        report.append("Positive 0x21 local IDs: ")
                .append(localHits)
                .append(" / 32\n");

        report.append("\n[4] ReadDataByCommonIdentifier 0x22 probes\n");
        String[] commonIds = {
                "F180", "F181", "F182", "F187",
                "F18A", "F18C", "F190", "0000"
        };

        for (String did : commonIds) {
            String request = "22" + did;
            String response = safeRequest(sds, request, 2200);

            report.append(request)
                    .append(" -> ")
                    .append(oneLine(response))
                    .append("\n");
        }

        report.append("\n[5] Alternate K-Line init paths supported by ELM327\n");
        report.append(
                "These tests only change adapter/init timing/baud temporarily, " +
                "then try the known read-only 1A91 identifier.\n"
        );

        boolean restore1 = probeKlineVariantIsolated(
                report,
                sds,
                "KWP slow init @ 10400, init address 0x12",
                "ATIB10",
                "ATTP4",
                true
        );

        boolean restore2 = false;
        boolean restore3 = false;

        if (restore1) {
            restore2 = probeKlineVariantIsolated(
                    report,
                    sds,
                    "KWP slow init @ 9600, init address 0x12",
                    "ATIB96",
                    "ATTP4",
                    true
            );
        } else {
            report.append(
                    "\nFurther alternate-init variants SKIPPED because normal SDS " +
                    "could not be proven restored after the first variant.\n"
            );
        }

        if (restore1 && restore2) {
            restore3 = probeKlineVariantIsolated(
                    report,
                    sds,
                    "KWP fast init @ 9600",
                    "ATIB96",
                    "ATTP5",
                    false
            );
        } else if (restore1) {
            report.append(
                    "\nFinal alternate-init variant SKIPPED because normal SDS " +
                    "could not be proven restored after the second variant.\n"
            );
        }

        boolean normalRestored = restore1 && restore2 && restore3;

        report.append("\n[6] Final normal Bandit SDS verification @ 10400\n");
        boolean finalRestore = restoreNormalSds(report, sds, "final restore");
        normalRestored = normalRestored && finalRestore;

        report.append("\nINTERPRETATION\n");
        report.append(
                "If an alternate init returns 5A91 while normal SDS is closed, " +
                "there is another reachable K-Line path using only the existing wire.\n"
        );
        report.append(
                "If all alternate init paths fail but normal SDS restores, the " +
                "remaining likely flash path needs either a proprietary raw bootloader " +
                "handshake that ELM cannot express or an additional ECU enable pin."
        );

        return new DensoReadOnlyTestResult(
                report.toString().trim(),
                String.join(", ", supported1A),
                String.join(", ", supported21),
                normalRestored
        );
    }

    private static boolean probeKlineVariantIsolated(
            StringBuilder report,
            SuzukiSds sds,
            String label,
            String baudCommand,
            String protocolCommand,
            boolean slowInit
    ) {
        report.append("\n").append(label).append("\n");

        // Every experiment starts from a freshly proven normal SDS state.
        if (!restoreNormalSds(report, sds, "pre-test restore")) {
            report.append("    Variant SKIPPED: normal SDS baseline could not be proven.\n");
            return false;
        }

        try {
            // Close the active normal protocol before deliberately changing
            // baud/init behaviour. This affects the adapter/link only.
            appendAt(report, sds, "ATPC", 2500);
            pause(450);

            appendAt(report, sds, baudCommand, 2500);
            appendAt(report, sds, "ATIIA12", 2500);
            appendAt(report, sds, protocolCommand, 2500);
            appendAt(report, sds, "ATSH8112F1", 2500);

            String init = sds.requestRaw(
                    slowInit ? "ATSI" : "ATFI",
                    slowInit ? 7000 : 5000
            );

            report.append(slowInit ? "ATSI" : "ATFI")
                    .append(" -> ")
                    .append(oneLine(init))
                    .append("\n");

            appendAt(report, sds, "ATSH8012F1", 2500);

            String id = safeRequest(sds, "1A91", 4000);
            report.append("Alternate-path 1A91 -> ")
                    .append(oneLine(id))
                    .append("\n");

            if (containsPositiveLocalIdentifier(id, 0x91)) {
                report.append("    *** Alternate path reached ECU ID successfully ***\n");
            }

        } catch (Exception e) {
            report.append("    Variant test error: ")
                    .append(e.getMessage())
                    .append("\n");
        } finally {
            report.append("Post-variant normal SDS recovery\n");
        }

        // Crucially, reset/reconfigure the ELM and prove the known-good
        // Bandit 1A91 read BEFORE another variant is attempted.
        return restoreNormalSds(report, sds, "post-test restore");
    }

    private static boolean restoreNormalSds(
            StringBuilder report,
            SuzukiSds sds,
            String stage
    ) {
        for (int attempt = 1; attempt <= 2; attempt++) {
            try {
                try {
                    sds.requestRaw("ATPC", 2200);
                } catch (Exception ignored) {}

                pause(attempt == 1 ? 500 : 1400);

                // initialise() begins with ATZ and then runs the exact known-good
                // Bandit ELM/SDS setup, including 10400-baud fast init.
                sds.initialise();
                pause(250);

                String id = safeRequest(sds, "1A91", 4500);
                report.append("    ")
                        .append(stage)
                        .append(" attempt ")
                        .append(attempt)
                        .append(": 1A91 -> ")
                        .append(oneLine(id))
                        .append("\n");

                if (containsPositiveLocalIdentifier(id, 0x91)) {
                    report.append("    Normal SDS PROVEN restored.\n");
                    return true;
                }

            } catch (Exception e) {
                report.append("    ")
                        .append(stage)
                        .append(" attempt ")
                        .append(attempt)
                        .append(" error: ")
                        .append(e.getMessage())
                        .append("\n");
            }
        }

        report.append("    Normal ATZ/re-init attempts failed; trying hard transport recovery.\n");

        try {
            if (sds.recoverKnownGoodSession()) {
                String id = safeRequest(sds, "1A91", 4500);
                report.append("    hard recovery: 1A91 -> ")
                        .append(oneLine(id))
                        .append("\n");

                if (containsPositiveLocalIdentifier(id, 0x91)) {
                    report.append("    Normal SDS PROVEN restored after hard reconnect.\n");
                    return true;
                }
            }
        } catch (Exception e) {
            report.append("    hard recovery error: ")
                    .append(e.getMessage())
                    .append("\n");
        }

        report.append(
                "    WARNING: normal SDS was not proven restored. " +
                "Stop alternate-init testing and cycle ignition/adapter power before continuing.\n"
        );
        return false;
    }

    private static void pause(long ms) {
        try {
            Thread.sleep(ms);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    private static void appendAt(
            StringBuilder report,
            SuzukiSds sds,
            String command,
            long timeoutMs
    ) {
        String response;

        try {
            response = sds.requestRaw(command, timeoutMs);
        } catch (IOException e) {
            response = "I/O ERROR: " + e.getMessage();
        }

        report.append(command)
                .append(" -> ")
                .append(oneLine(response))
                .append("\n");
    }

    private static String printablePayloadAfter(
            String response,
            int positiveService,
            int localId
    ) {
        if (response == null) return "";

        String hex = compactHex(response);
        String marker = String.format(
                Locale.US,
                "%02X%02X",
                positiveService & 0xFF,
                localId & 0xFF
        );

        int p = hex.indexOf(marker);
        if (p < 0) return "";

        String payload = hex.substring(p + marker.length());
        StringBuilder ascii = new StringBuilder();

        for (int i = 0; i + 1 < payload.length(); i += 2) {
            int value;

            try {
                value = Integer.parseInt(payload.substring(i, i + 2), 16);
            } catch (NumberFormatException e) {
                break;
            }

            if (value == 0x00 || value == 0xFF) continue;

            if (value >= 0x20 && value <= 0x7E) {
                ascii.append((char)value);
            } else {
                ascii.append('.');
            }
        }

        return ascii.toString();
    }

    private static String compactHex(String value) {
        if (value == null) return "";
        return value.toUpperCase(Locale.US)
                .replaceAll("[^0-9A-F]", "");
    }

    static String negativeResponseExplanation(String response, int service) {
        if (response == null) return null;

        String hex = response.toUpperCase(Locale.US)
                .replaceAll("[^0-9A-F]", "");

        String marker = String.format(Locale.US, "7F%02X", service);
        int p = hex.indexOf(marker);

        if (p < 0 || p + 6 > hex.length()) return null;

        int nrc;

        try {
            nrc = Integer.parseInt(hex.substring(p + 4, p + 6), 16);
        } catch (NumberFormatException e) {
            return null;
        }

        String meaning;

        switch (nrc) {
            case 0x10: meaning = "general reject"; break;
            case 0x11: meaning = "service not supported"; break;
            case 0x12: meaning = "sub-function not supported / invalid format"; break;
            case 0x21: meaning = "busy - repeat request"; break;
            case 0x22: meaning = "conditions not correct"; break;
            case 0x31: meaning = "request out of range"; break;
            case 0x33: meaning = "security access denied"; break;
            case 0x35: meaning = "invalid key"; break;
            case 0x36: meaning = "security attempts exceeded"; break;
            case 0x37: meaning = "required time delay not expired"; break;
            case 0x40: meaning = "download not accepted"; break;
            case 0x50: meaning = "upload not accepted"; break;
            case 0x71: meaning = "transfer suspended"; break;
            case 0x72: meaning = "transfer aborted"; break;
            case 0x74: meaning = "illegal address in block transfer"; break;
            case 0x75: meaning = "illegal byte count in block transfer"; break;
            case 0x76: meaning = "illegal block transfer type"; break;
            case 0x77: meaning = "block transfer checksum error"; break;
            case 0x78: meaning = "response pending"; break;
            case 0x79: meaning = "incorrect byte count during block transfer"; break;
            case 0x80: meaning = "service not supported in active session"; break;
            default:
                meaning = "negative response";
        }

        return String.format(
                Locale.US,
                "NRC 0x%02X (%s)",
                nrc,
                meaning
        );
    }

    private static String oneLine(String value) {
        if (value == null) return "";
        return value.replace('\r', ' ')
                .replace('\n', ' ')
                .trim();
    }

    private static String toHex(byte[] bytes) {
        StringBuilder s = new StringBuilder(bytes.length * 2);
        for (byte b : bytes) {
            s.append(String.format(Locale.US, "%02x", b & 0xFF));
        }
        return s.toString();
    }
}
